---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: null
sections:
  - type: document
    label: Global Site Config
    path: site-metadata.json
    templates:
      - config
  - type: document
    label: Medium Landing
    path: src/pages/medium.md
    templates:
      - MediumLayout
  - type: document
    label: containerLayout
    path: src/pages/tos.md
    templates:
      - containerLayout
  - type: directory
    path: src/pages
    match: '**/*'
    exclude: '{medium.md,tos.md}'
    label: singleColumnLayouts
    create: all
    templates:
      - singleColumnLayout
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
